//
// Created by Kevin Williams on 9/17/22.
//

#ifndef ESPROVER_DOCROOT_H
#define ESPROVER_DOCROOT_H
static const char * docroot = "<!DOCTYPE html>\n"
                              "<html lang='en'>\n"
                              "<head>\n"
                              "    <meta charset='UTF-8'>\n"
                              "    <title>ESP Rover</title>\n"
                              "    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/nipplejs/0.9.1/nipplejs.min.js'></script>\n"
                              "    <script type='Module' src='https://cdnjs.cloudflare.com/ajax/libs/fetch/3.6.2/fetch.min.js'></script>\n"
                              "    <script type='text/javascript'>\n"
                              "        let _delay = 200;\n"
                              "        let _prev_heading = -1;\n"
                              "        let _prev_power = -1;\n"
                              "        let _prev_cmd = '';\n"
                              "\n"
                              "        let _cmd = 0;\n"
                              "        let _heading = 0;\n"
                              "        let _power = 0;\n"
                              "\n"
                              "        time=setInterval(function(){\n"
                              "            if(_cmd === _prev_cmd && _heading === _prev_heading && _power === _prev_power) {\n"
                              "                return;\n"
                              "            }\n"
                              "                const requestOptions = {\n"
                              "                    method: 'POST',\n"
                              "                    headers: { 'Content-Type': '*/*'},\n"
                              "                    body: JSON.stringify({ cmd: _cmd, heading: _heading, power: _power })\n"
                              "                };\n"
                              "\n"
                              "                fetch('/api', requestOptions)\n"
                              "                    .then((resp) => console.log(resp.statusText))\n"
                              "                    .catch((err) => console.log(err));\n"
                              "                _prev_cmd = _cmd;\n"
                              "                _prev_heading = _heading;\n"
                              "                _prev_power = _power;\n"
                              "\n"
                              "        },_delay);\n"
                              "\n"
                              "        function drive(cmd, heading, power) {\n"
                              "            document.getElementById('results').innerText = `h: ${Math.round(heading)}, p: ${Math.round(power*100)} %`;\n"
                              "            _cmd = cmd; _heading = heading; _power = power;\n"
                              "        }\n"
                              "\n"
                              "    </script>\n"
                              "    <style>\n"
                              "        html {font-family:Helvetica;margin:0; height: 100%; overflow: clip;}\n"
                              "        .container {width: 100%; height: 100px; overflow: hidden}\n"
                              "        .joystic-container {}\n"
                              "        .results {margin: auto; width: 100%; font-size:1.5rem; text-align: center}\n"
                              "        h1 {color:#0F3376; padding:1vh; text-align:center}\n"
                              "    </style>\n"
                              "</head>\n"
                              "<body>\n"
                              "<h1>ESP Rover</h1>\n"
                              "<div class=\"results\" id=\"results\"></div>\n"
                              "<div class='container'>\n"
                              "    <div id='joystick' class='joystic-container'></div>\n"
                              "    <div id='joystick2' class='joystic-container'></div>\n"
                              "</div>\n"
                              "\n"
                              "<script>\n"
                              "    let btnSize= 200;\n"
                              "    let joy = nipplejs.create({\n"
                              "        zone: document.getElementById('joystick'),\n"
                              "        mode: 'static',\n"
                              "        position: {left: '25%', top: '50%'},\n"
                              "        color: 'blue',\n"
                              "        size: btnSize\n"
                              "    });\n"
                              "    joy.on('move', function (evt, data) {\n"
                              "        let heading = data.angle.degree; //Math.round(data.angle.degree/15)*15;\n"
                              "        let power = data.distance/(btnSize/2.0); //(Math.round(data.distance/20)*20/(btnSize/2.0));\n"
                              "        if(power==0) {\n"
                              "            heading=0;\n"
                              "        }\n"
                              "        drive('drive',heading, power);\n"
                              "    });\n"
                              "    joy.on('end', function (evt, data) {\n"
                              "        drive('drive',0,0);\n"
                              "    });\n"
                              "\n"
                              "    let joy2 = nipplejs.create({\n"
                              "        zone: document.getElementById('joystick2'),\n"
                              "        mode: 'static',\n"
                              "        position: {left: '75%', top: '50%'},\n"
                              "        color: 'blue',\n"
                              "        size: btnSize\n"
                              "    });\n"
                              "    joy2.on('move', function (evt, data) {\n"
                              "        let heading = data.angle.degree;\n"
                              "        heading = (heading >=90 && heading <= 270) ? -1.0 : 1.0;\n"
                              "        let power = data.distance/(btnSize/2.0);\n"
                              "        if(power === 0) {\n"
                              "            heading=0;\n"
                              "        }\n"
                              "        drive('rotate',heading, power);\n"
                              "    });\n"
                              "    joy2.on('end', function (evt, data) {\n"
                              "        drive('rotate',0,0);\n"
                              "    });\n"
                              "</script>\n"
                              "</body>\n"
                              "</html>";
#endif //ESPROVER_DOCROOT_H
