//
// Created by Kevin Williams on 9/17/22.
//

#ifndef ESPROVER_DOCROOT_H
#define ESPROVER_DOCROOT_H
static const char * docroot = "<!DOCTYPE html>\n"
                              "<html lang='en'>\n"
                              "<head>\n"
                              "    <meta charset='UTF-8'>\n"
                              "    <title>Title</title>\n"
                              "    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/nipplejs/0.9.1/nipplejs.min.js'></script>\n"
                              "    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/fetch/3.6.2/fetch.min.js'></script>\n"
                              "    <script type='text/javascript'>\n"
                              "        let _heading = 0;\n"
                              "        let _power = 0;\n"
                              "        bounce = 0;\n"
                              "        async function drive(heading, power) {\n"
                              "            if(heading == _heading && power == _power) {bounce = bounce + 1;}\n"
                              "            document.getElementById('results').innerText = `h: ${heading}, p: ${power} %`;\n"
                              "            let heading_changed = (heading != _heading || power != _power);\n"
                              "            if((bounce>3 && heading_changed) || (heading_changed && power == 0)){\n"
                              "                const requestOptions = {\n"
                              "                    method: 'POST',\n"
                              "                    headers: { 'Content-Type': '*/*'},\n"
                              "                    body: JSON.stringify({ cmd: 'drive', heading: heading, power: power })\n"
                              "                };\n"
                              "                await fetch('/api', requestOptions);\n"
                              "                bounce = 0;\n"
                              "            }\n"
                              "            _heading = heading;\n"
                              "            _power = power;\n"
                              "        }\n"
                              "    </script>\n"
                              "    <style>\n"
                              "        html {font-family:Helvetica;display:inline-block;margin:0px auto;text-align:center;}\n"
                              "        .container {width: 100%; margin: auto;}\n"
                              "        .results {bottom: 20px; position: absolute; margin: auto; width: 100%; font-size:3.0rem;}\n"
                              "        @media screen and (min-width:800px) {.container{width:50%;}  }\n"
                              "        h1 {color:#0F3376;padding:2vh;}\n"
                              "    </style>\n"
                              "</head>\n"
                              "<body>\n"
                              "<h1>ESP Rover</h1><div class='container'><div id='joystick' ></div></div><div class=\"results\" id=\"results\"></div>\n"
                              "<script>\n"
                              "    let joy = nipplejs.create({\n"
                              "        zone: document.getElementById('joystick'),\n"
                              "        mode: 'static',\n"
                              "        position: {left: '50%', top: '50%'},\n"
                              "        color: 'blue',\n"
                              "        size: 400\n"
                              "    });\n"
                              "    joy.on('move', function (evt, data) {\n"
                              "        let heading = Math.round(data.angle.degree/15)*15;\n"
                              "        let power = (Math.round(data.distance/20)*20/200);\n"
                              "        if(power==0) {\n"
                              "            heading=0;\n"
                              "        }\n"
                              "        drive(heading, power);\n"
                              "    });\n"
                              "    joy.on('end', function (evt, data) {\n"
                              "        drive(0,0);\n"
                              "    });\n"
                              "</script>\n"
                              "</body>\n"
                              "</html>";
#endif //ESPROVER_DOCROOT_H
